"""5 creative angles + 5 hook-copy lines, generated by Claude Haiku."""

from __future__ import annotations

import logging

from ..cost_tracker import CostTracker
from ..llm import call_haiku_json
from ..schemas import (
    CreativeAngle,
    CreativesBlock,
    HookCopy,
    MetaAdsSignal,
    ProductFingerprint,
    TrendsSignal,
)

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = (
    "You are a direct-response creative strategist specialized in Meta + TikTok "
    "ads for dropshippers. Generate concise, conversion-oriented ideas grounded "
    "in the data provided. Return ONLY valid JSON, no markdown, no commentary."
)

USER_TEMPLATE = """Product fingerprint:
- primary_keyword: {primary}
- category: {category}
- attributes: {attributes}

Trend context:
- related rising queries: {rising}
- current peak countries: {countries}
- competitor advertisers (Meta): {advertisers}

Task: generate 5 distinct creative angles and 5 short-form hook-copy lines.
Return JSON with this exact shape:
{{
  "angles": [
    {{"name": "string", "description": "string (≤140 chars)",
      "target_emotion": "string", "format_hint": "UGC|static|carousel|talking-head"}},
    ...
  ],
  "hooks": [
    {{"text": "string (≤80 chars)", "style": "string"}},
    ...
  ]
}}
"""


async def generate(
    fingerprint: ProductFingerprint,
    trends: TrendsSignal,
    meta: MetaAdsSignal,
    cost: CostTracker,
) -> CreativesBlock:
    user_prompt = USER_TEMPLATE.format(
        primary=fingerprint.primary_keyword,
        category=fingerprint.category,
        attributes=", ".join(fingerprint.product_attributes) or "n/a",
        rising=", ".join(trends.related_queries_rising[:5]) or "n/a",
        countries=", ".join(g.country for g in trends.geography[:5]) or "n/a",
        advertisers=", ".join(meta.top_advertisers[:5]) or "n/a",
    )

    payload = await call_haiku_json(
        system=SYSTEM_PROMPT,
        user=user_prompt,
        cost=cost,
        operation="generate_creatives",
        max_tokens=700,
    )

    return _coerce(payload)


def _coerce(payload: dict) -> CreativesBlock:
    raw_angles = payload.get("angles") or []
    raw_hooks = payload.get("hooks") or []

    angles: list[CreativeAngle] = []
    for a in raw_angles[:5]:
        if not isinstance(a, dict):
            continue
        try:
            angles.append(
                CreativeAngle(
                    name=str(a.get("name", "")).strip()[:60] or "Untitled",
                    description=str(a.get("description", "")).strip()[:200],
                    target_emotion=str(a.get("target_emotion", "")).strip()[:40] or "curiosity",
                    format_hint=str(a.get("format_hint", "UGC")).strip()[:20] or "UGC",
                )
            )
        except Exception:
            continue

    hooks: list[HookCopy] = []
    for h in raw_hooks[:5]:
        if isinstance(h, str):
            hooks.append(HookCopy(text=h[:120]))
            continue
        if not isinstance(h, dict):
            continue
        text = str(h.get("text", "")).strip()
        if not text:
            continue
        hooks.append(
            HookCopy(
                text=text[:120],
                style=str(h.get("style", "")).strip()[:40] or "problem-agitate",
            )
        )

    return CreativesBlock(angles=angles, hooks=hooks)
